rocket-pool/smartnode

README.md
Hey guys, thanks so much for renaming this! Seriously confused me after running `stop` thinking it was `pause` and now I'm back to resyncing 😆
=> Update README to reflect new `terminate` command

rocketpool-cli/minipool/withdraw.go
tested by @Xer0 https://discordapp.com/channels/405159462932971535/468923220607762485/803064943560753213
=> fix withdraw

go.mod, go.sum
update to new version of rocketpool-go so it will compile
=> update rocketpool-go to version using geth 1.10

rocketpool/node/stake-prelaunch-minipools.go
Hi,
First of all, congratulations on the amazing work!
While testing the beta on Fedora 33 with Docker CE 20, I came across a bug where the validator was not properly restarted:
```
2021/03/29 19:23:10 1 minipool(s) are ready for staking...
2021/03/29 19:23:10 Staking minipool 0xC497F64d65D1eb014529F4767f87d4BC8A9Ae1cA...
2021/03/29 19:23:33 Successfully staked minipool 0xC497F64d65D1eb014529F4767f87d4BC8A9Ae1cA.
2021/03/29 19:23:33 Restarting validator process with command '/root/.rocketpool/chains/eth2/restart-validator.sh'...
2021/03/29 19:23:33 Could not restart validator process: fork/exec /root/.rocketpool/chains/eth2/restart-validator.sh: no such file or directory
```
It seems that the smartnode may not always correctly detect that it running inside a container.
After applying and …
=> Tentative fix for container detection code

rocketpool/watchtower/submit-withdrawable-minipools.go
This was a request from Dave. It augments the Watchtower's `getMinipoolWithdrawableDetails()` function by checking to see if the minipool has received at least as much ETH as it was expected to get from an eth2 validator withdrawal prior to marking it as withdrawable. The origin of the ETH doesn't matter; if someone besides the SWC wants to donate ETH to the node operator, more power to them.
=> New Withdrawable Check

rocketpool-cli/node/deposit.go, shared/services/services.go
=> Check eth2 sync status during deposits

shared/services/wallet/keystore/nimbus/keystore.go
I'm guessing this was some copy and paste carryover that didn't get updated. Changes made only to in-line comments only.
=> Revised in line comment from Lighthouse -> Nimbus

rocketpool-cli/minipool/vanity.go
Reuse a keccak hasher across salt search attempts instead of creating a new one for each hash.
Speeds up vanity salt searches by at least 30% on my machine (AMD Ryzen 7 2700X Eight-Core with HT enabled).
NB: The following output depends on PR #190 which adds back functionality for `-a`, but for convenience, this PR does not include that commit.
```
jacob@Joshua:~/smartnode/rocketpool-cli (jms/vanity-2)$ ./build.sh 
jacob@Joshua:~/smartnode/rocketpool-cli (jms/vanity-2)$ ./rocketpool-cli-linux-amd64 minipool find-vanity-address -a 16 -p 0x123456
Running with 16 threads.
At salt 0x9641d0... 5.000144919s (1.96M salts/sec)
At salt 0x134c080... 10.000109476s (2.07M salts/sec)
At salt 0x1dfebb0... 15.002520997s (2.24M salts/sec)
Found on thread 12: salt 0x25bca1c = …
```
=> Speed up vanity salt mining by re-using a keccak hasher per worker thread

rocketpool-cli/wallet/utils.go
2 users have been stung by not RTFM.
=> Bold parts of wallet mnemonic prompt for clarity

rocketpool-cli/odao/proposals.go, rocketpool-cli/odao/vote-proposal.go
Adding oDAO proposer name to `rp o o l`, `rp o o d`, and `rp o o v`.
=> 1058 - Adding proposer name to proposal details.

rocketpool/api/debug/commands.go, rocketpool/api/node/sync.go, rocketpool/api/service/status.go, shared/services/bc-manager.go, shared/services/ec-manager.go, shared/services/requirements.go, shared/types/eth2/types.go
This should resolve https://github.com/rocket-pool/smartnode/issues/218
NB This PR will be easier to read if https://github.com/rocket-pool/smartnode/pull/217/files is merged first.
Otherwise, just look at the top diff: `https://github.com/rocket-pool/smartnode/pull/219/commits/0ad4f6263cf88f246b77e9ed442d7a545c080c0b`
=> Allow node/watchtower to use fallback clients

rocketpool-cli/node/smoothing-pool.go
=> Fix comment

rocketpool/node/collectors/node-collector.go
This PR fixes a bug in the rocketpool_node_unclaimed_eth_rewards metric.
=> Fix accumulation of SP unclaimed ETH rewards.

rocketpool-cli/service/commands.go, rocketpool-cli/service/service.go
Adds a --force flag to the export-eth1-data command to ignore the free space check on the target folder.
Closes #230
=> Add --force to the export-eth1-data cmd.

rocketpool/api/node/sync.go, rocketpool/api/service/status.go, shared/services/ec-manager.go, shared/services/requirements.go, shared/types/api/service.go
=> Add error for fallbacks using an incorrect network.

shared/services/rewards/manager.go
This PR fixes an untreated error that caused a SIGSEGV.
Closes #285
=> Fix untreated error causing SIGSEGV.

shared/services/config/external-configs.go
Fix string with dangling %s, and adding connection examples as requested on issue 281.
Closes #281.
=> Remove %s and add examples.

rocketpool-cli/rocketpool-cli.go
=> Update app.Copyright from rocketpool-cli.go

rocketpool-cli/service/commands.go
=> Adding --yes flag to export-eth1-data cmd.

rocketpool-cli/wallet/bip39/mnemonic-validator.go
=> Fix panic when the word from the wordlist being compared is short

shared/services/config/nimbus-config.go
Hope this makes sense to merge into the new Atlas branch
=> Update to v23.3.2

rocketpool-cli/network/dao-proposals.go
Fixes formatting of the quorum string after a change on the Snapshot API.
Also, fixes Identifying the correct voted choices.
Closes #336
=> Fix snapshot data

rocketpool-cli/node/sync.go
https://go.dev/play/p/Mo5TbcJHPwD to audit the cap
before:
```
jacob@rocketnuc:~🚀🚀🚀 $ rocketpool node sync
Your Smartnode is currently using the Ethereum Mainnet.
Your eth2 client is on the correct network.
Your primary execution client is fully synced.
Your fallback execution client is fully synced.
Your primary consensus client is still syncing (100.00%).
Your fallback consensus client is fully synced.
```
after:
```
jacob@rocketnuc:~🚀🚀🚀 $ ./rocketpool-cli-linux-amd64 node sync
Your Smartnode is currently using the Ethereum Mainnet.
Your eth2 client is on the correct network.
Your primary execution client is fully synced.
Your fallback execution client is fully synced.
Your primary consensus client is still syncing (99.99%).
Your fallback consensus client is fully synced.
```
=> Refactor sync progress printing, cap reported progress at 99.99%

rocketpool/api/node/distributor.go
=> Add missing nonce override check.

rocketpool-cli/service/config/config-form.go, rocketpool-cli/service/config/textbox-modal-layout.go
Trims white spaces from the beginning and end of form fields and on the wizard.
Closes #349
=> Trimming spaces from form fields.

rocketpool-cli/service/service.go
closes https://github.com/rocket-pool/smartnode/issues/376
=> Make the slash timer messaging more explicit, ominous, and link to the docs

shared/services/rocketpool/client.go, shared/services/rocketpool/command.go
closes https://github.com/rocket-pool/smartnode/issues/380
=> change the way smartnode downloads and runs the install script to catch errors with the download better

shared/services/config/rocket-pool-config.go
=> Removing extra comma.

rocketpool/watchtower/submit-network-balances.go, rocketpool/watchtower/submit-rpl-price.go, shared/services/config/smartnode-config.go
Remove the first Houston submission parameter calculating it instead.
=> Remove the first Houston submission parameter

rocketpool-cli/wallet/recover.go
=> Prompt if the user would prefer to skip key recovery when recovering wallet with unsynced clients

go.sum, rocketpool-cli/service/service.go, rocketpool/api/service/commands.go, rocketpool/api/service/terminate.go, shared/services/config/consensus-common-config.go, shared/services/config/mev-boost-config.go, shared/services/config/smartnode-config.go, shared/services/ec-manager.go, shared/services/rewards/generator.go, shared/services/rewards/rewards-interval-info.go, shared/services/rocketpool/service.go, shared/services/state/utils.go, shared/services/wallet/node.go, shared/utils/cli/utils.go
Removing the Prater test network and related Goerli logic.
=> Prater removal

shared/services/beacon/client/std-http-client.go
Filter out duplicate pubkeys
Closes #442
=> Filter out duplicate pubkeys

rocketpool-cli/service/service.go
=> Add MEV-Boost version in `rocketpool service version`.

rocketpool-cli/node/status.go, rocketpool-cli/service/config/settings-native-smartnode.go, rocketpool-cli/service/service.go, rocketpool/api/network/commands.go, rocketpool/api/network/voting.go, rocketpool/api/pdao/percentages.go, rocketpool/node/node.go, shared/services/config/consensus-common-config.go, shared/services/config/reth-params.go, shared/services/config/rocket-pool-config.go, shared/services/rocketpool/template/template.go, shared/types/api/node.go
I found a few things that needed to be fixed and tweaked a few other things while migrating to v2 in https://github.com/rocket-pool/smartnode/commit/545728acaf46e74f5b58625f39e031e95f3422e2, and am offering them up as a backport to v1.
=> Some fixes / updates found during the v2 migration

rocketpool-cli/minipool/close.go
Non-functional control flow changes to outdent a bit and use `continue` instead of a wall of if-else
Click to review without whitespace (simplified diff):
https://github.com/rocket-pool/smartnode/pull/488/files?diff=unified&w=1
https://github.com/rocket-pool/smartnode/pull/488/files?diff=split&w=1
=> Refactor close() confirmation control flow for simplicity

.github/workflows/build.yml, .github/workflows/unit-tests.yml, rocketpool-cli/minipool/reduce-bond.go, rocketpool-cli/minipool/rescue-dissolved.go, rocketpool-cli/node/create-vacant-minipool.go, rocketpool-cli/node/deposit.go, rocketpool-cli/node/smoothing-pool.go, rocketpool-cli/node/status.go, rocketpool-cli/node/sync.go, rocketpool-cli/node/utils.go, rocketpool-cli/service/service.go, rocketpool-cli/wallet/export.go, rocketpool-cli/wallet/utils.go, rocketpool/api/debug/validators.go, rocketpool/api/node/deposit.go, rocketpool/node/collectors/node-collector.go, rocketpool/watchtower/generate-rewards-tree.go, shared/services/beacon/client/std-http-client.go, shared/services/gas/gas.go, shared/services/requirements.go, shared/services/rocketpool/odao.go, shared/utils/cli/migration/import-key.go, shared/utils/cli/utils.go, shared/utils/eth1/eth1.go
See https://github.com/jshufro/smartnode/pull/7 for an example of this working
=> Fix printf/printlns that cause `go test` to fail, add unit test and build CI

.github/workflows/lint.yml, rocketpool/api/node/set-stake-rpl-for-allowed.go, shared/services/rewards/types.go
Annotates the un-formatted files:
=> Add goimports lint github action

rocketpool/api/pdao/claimable-bonds.go
This PR updates the state comparison for challenges that should be claimable.
=> Fix claimable challenge states.

CHANGELOG.md
Created a Changelog, starts at current version v1.12.0 and goes back to v1.10.0.
Closes https://github.com/rocket-pool/smartnode/issues/391
***Addressing comment by [0xfornax](https://github.com/0xfornax) to target master and push from my master instead of pushing from my v2 and targeting v2 (from previous pull request https://github.com/rocket-pool/smartnode/pull/492)***
=> Func: Adding Changelog

rocketpool-cli/pdao/get-voting-power.go, rocketpool/api/pdao/get-voting-power.go, shared/types/api/pdao.go
new output for `rp p vp`:
```
tpan@tpan-meerkat:~$ dev p vp
== Node Voting Power ==
The node has been initialized for onchain voting.
The node has a voting delegate of 0xbD7c2292ae7882c2c30A7d1d42AF253305b61435 which can represent it when voting on Rocket Pool onchain governance proposals.
Your current voting power: 36.6886491652
```
=> Add more info to rp pdao voting-power

rocketpool-daemon/api/service/client-status.go, rocketpool-daemon/api/tx/batch-sign-txs.go, rocketpool-daemon/api/tx/batch-submit-txs.go, rocketpool-daemon/api/wallet/export.go, rocketpool-daemon/api/wallet/send-message.go, v2.md
=> Updated the v2 doc, some improvements ported from HD

rocketpool-cli/node/status.go, rocketpool-cli/service/service.go, shared/services/config/exporter-config.go, shared/services/config/geth-params.go, shared/services/config/grafana-config.go, shared/services/config/prometheus-config.go
Update patch notes;
New metrics image versions;
Add Geth archive node;
Improve Snapshot/onchain delegate messages.
=> Improve governance instructions

rocketpool-cli/pdao/proposals.go
Before:
```
Proposal ID:            3
Message:                invite peteris (0xc80ed2a9cD0e18Ab662edE167CBc96B7C5B59970) to the security council
Payload:                proposalSecurityInvite(peteris,0xc80ed2a9cD0e18Ab662edE167CBc96B7C5B59970)
Payload (bytes):        f944c19f0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000c80ed2a9cd0e18ab662ede167cbc96b7c5b5997000000000000000000000000000000000000000000000000000000000000000077065746572697300000000000000000000000000000000000000000000000000
Proposed by:            0xc80ed2a9cD0e18Ab662edE167CBc96B7C5B59970
Created at:             03 May 24 08:22 PDT
State:                  Active (Phase 1)
Phase 1 end:            03 May 24 22:22 PDT
Voting power required:  546.2832464273
Voting power for: …
```
=> Add time diff to pdao details menu

rocketpool-cli/pdao/proposals.go
forgot to add this to pending proposals 
before:
```
...
Proposed by:            0xE8325F5f4486c2FF2AC7B522Fbc9eB249d46C936
Created at:             08 May 24 19:33 PDT, was 2h58m44s ago
State:                  Pending
Voting start:           08 May 24 23:33 PDT
Challenge window:       30m0s
Voting power required:  1219.1447578732
Voting power for:       0.0000000000
Voting power against:   0.0000000000
Voting power abstained: 0.0000000000
Voting power against:   0.0000000000
Node has voted:         no
```
after:
```
...
Proposed by:            0xE8325F5f4486c2FF2AC7B522Fbc9eB249d46C936
Created at:             08 May 24 19:33 PDT, was 2h58m44s ago
State:                  Pending
Voting start:           08 May 24 23:33 PDT, in 1h1m15s
Challenge window:       30m0s
Voting power required: …
```
=> Fix missing time diff output

shared/services/rewards/generator-impl-v8.go
This fixes vanilla generator 8's non-conformance with rewards spec v8.
=> Fixed v8 for non-RRs

rocketpool-cli/service/config/settings-mev-boost.go, shared/services/config/mev-boost-config.go, shared/types/config/types.go, shared/version.go
Adding the Global and Regional Titan relays.
https://docs.titanrelay.xyz/
=> Add the Titan relays

rocketpool-cli/pdao/proposals.go, rocketpool-cli/pdao/status.go
sorry halolololololololololo 🐝 
```
21: invite peteris (0xc80ed2a9cD0e18Ab662edE167CBc96B7C5B59970) to the security council - Proposed by: 0x7F1E6E06bda5fa4251b73CF933040efaC5d39983
22: invite peteris (0xc80ed2a9cD0e18Ab662edE167CBc96B7C5B59970) to the security council - Proposed by: 0x7F1E6E06bda5fa4251b73CF933040efaC5d39983
24: one-time spend for invoice senddeeznuts - Proposed by: 0xE8325F5f4486c2FF2AC7B522Fbc9eB249d46C936
25: 2️⃣🐝🎬 or not 2️⃣🐝🎬, this is the script:
Bee Movie
By Jerry Seinfeld
NARRATOR:
(Black screen with text; The sound of buzzing bees can be heard)
According to all known laws
of avia - Proposed by: 0x7F1E6E06bda5fa4251b73CF933040efaC5d39983
2 Defeated proposal(s):
15: invite peteris (0xc80ed2a9cD0e18Ab662edE167CBc96B7C5B59970) to the security council - Proposed by: …
```
=> Add 200 character limit to proposal list output.

rocketpool-cli/pdao/execute-proposal.go
following the same logic used in `pdao/status.go` and `pdao/proposals.go`
ref: https://github.com/rocket-pool/smartnode/blob/master/rocketpool-cli/pdao/status.go#L183 and https://github.com/rocket-pool/smartnode/blob/master/rocketpool-cli/pdao/proposals.go#L97
=> sanitize message in execute-proposal.go

shared/services/bc-manager.go, shared/services/ec-manager.go, shared/services/services.go, shared/types/api/service.go
Reverts rocket-pool/smartnode#532
=> Revert "Moving away from the deprecated network id and checking chain ids"

shared/services/config/prysm-config.go, shared/services/config/teku-config.go
=> Prysm v5.0.4

rocketpool-cli/pdao/commands.go, rocketpool-cli/pdao/initialize-voting.go
```
tpan@tpan-meerkat:~$ dev p iv
Would you like to initialize voting with a delegate? [y/n]
y
Please enter the delegate's address:
```
=> Merge initialize voting commands, prompts for an option instead

go.mod, go.sum, rocketpool-daemon/api/service/client-status.go, rocketpool-daemon/api/service/restart-vc.go, rocketpool-daemon/common/services/requirements.go, rocketpool-daemon/node/collectors/node-collector.go, rocketpool-daemon/node/distribute-minipools.go, rocketpool-daemon/node/manage-fee-recipient.go, rocketpool-daemon/node/stake-prelaunch-minipools.go
=> Update NMC to v0.5.0

rocketpool-daemon/api/minipool/rescue-dissolved-details.go
The minipool version info was missing.
=> Fix minipool rescue command

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yml, build.sh, docker/cli.dockerfile, docker/daemon-build.dockerfile, go.mod, install/packages/changelog.sh, install/packages/debian/debian/control, install/packages/debian/package.dockerfile
Upgrading Go to v1.22.
Using the new deb-builder image (v1.0.2).
=> Upgrading go to v1.22.

rocketpool-cli/service/config/settings-mev-boost.go, shared/services/config/mev-boost-config.go, shared/types/config/types.go
Considering this [announcement](https://x.com/titanrelayxyz/status/1829202005354807374) the Eden relay will be removed from the next release
=> Remove the Eden relay.

rocketpool-daemon/watchtower/submit-network-balances.go, rocketpool-daemon/watchtower/submit-rpl-price.go
Replicate the v1 changes from https://github.com/rocket-pool/smartnode/pull/663
=> v2 Fix price/balances submission check.

rocketpool-daemon/common/rewards/generator.go
Replicate the V1 fix https://github.com/rocket-pool/smartnode/pull/674/ for V2.
=> Fix the tree version iterator.

rocketpool/watchtower/submit-rpl-price.go, rocketpool/watchtower/utils/utils.go
Prices/balances will only be calculated after the interval duration in seconds has passed.
=> Fix price/balance submission check

rocketpool-daemon/watchtower/submit-network-balances.go, rocketpool-daemon/watchtower/submit-rpl-price.go, rocketpool-daemon/watchtower/utils/utils.go
Replicating this fix https://github.com/rocket-pool/smartnode/pull/680 from v1.
=> Port submission fix from v1

rocketpool-daemon/common/voting/utils.go, shared/types/voting.go
Replicate https://github.com/rocket-pool/smartnode/pull/691 on v2.
=> [V2] Snapshot field updated from string -> int64

shared/services/config/prysm-config.go
Adding the `--p2p-quic-port` setting with a default 8001 port
=> Prysm v5.2.0

rocketpool-cli/pdao/one-time-spend.go, rocketpool-cli/pdao/recurring-spend-update.go, rocketpool-cli/pdao/recurring-spend.go
=> Issue 753 - Allow whitespaces on the contract name

shared/services/rewards/generator.go
We're having issues on Hoodi to find the approximator impl for interval 0.
=> Fix to find the apporximator for the first interval

shared/services/config/mev-boost-config.go
Swapped
https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.max-profit.builder.hoodi.blxrbdn.com?id=rocketpool
for 
https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.hoodi.blxrbdn.com?id=rocketpool
=> Relay DNS Correction

rocketpool/watchtower/submit-rewards-tree-stateless.go
There was a bug as crypto.Keccak256Hash([]byte("rewards.snapshot.submitted.node"), nodeAddress.Bytes(), indexBuffer)) would not map to the Solidity code storing the bool value we need .
=> Fix packing bytes when checking if node submitted

rocketpool-cli/service/service.go
remove duplicate package imports
=> chore: remove duplicate package imports

rocketpool/watchtower/submit-rpl-price.go
Price submissions were using the latest submission block timestamp instead of the slot timestamp.
=> Use last submission event instead of block header

shared/services/beacon/client/std-http-client.go
Allows us to request a block using the "finalized" tag.
=> Using %s so we can request a 'finalized' block

bindings/utils/state/common.go, bindings/utils/state/network.go, bindings/utils/state/odao.go
This reverts commit 9d138f7e3c72b4ca59843763b67c366fb66ce223.
=> PARTIAL Revert "Refactor bindings/utils/state slightly"

shared/services/rocketpool/pdao.go
=> chore: fix function name in comment

bindings/legacy/v1.0.0/utils/address_generation.go, bindings/legacy/v1.1.0-rc1/rewards/rewards.go, bindings/legacy/v1.1.0/utils/address_generation.go, bindings/rewards/rewards.go, bindings/utils/address_generation.go, rocketpool-cli/network/commands.go, rocketpool-cli/pdao/set-signalling-address.go, rocketpool-cli/service/config/directional-modal.go, rocketpool-cli/service/config/pseudomodal.go
fix some minor issues in the comments
=> chore: fix some minor issues in the comments

rocketpool-cli/node/rewards.go, rocketpool/api/node/rewards.go
- Updated the text in `node rewards`
- Fixes a case where RPL apr displays `NaN` 
- Removed some old comments in the API
=> Improvements to `rocketpool node rewards`

bindings/settings/protocol/auction.go, bindings/settings/protocol/proposals.go, rocketpool-cli/pdao/percentages.go, rocketpool-cli/pdao/vote-proposal.go, rocketpool-cli/service/config/form.go, shared/services/alerting/alertmanager/client/silence/get_silences_parameters.go, shared/services/rewards/files.go
fix some minor issues in comments
=> chore: fix some minor issues in comments

rocketpool/node/metrics-exporter.go, rocketpool/rocketpool.go, rocketpool/watchtower/metrics-exporter.go
=> Fix node/watchtower metrics port

shared/services/rocketpool/assets/install/scripts/start-ec.sh
=> Fix Nethermind pruning mode

shared/services/rocketpool/assets/scripts/install.sh
Removed software-properties-common dependency (unavailable on Debian 13). 
Checking if Docker is installed. If not, check if a candidate for installation is available using `apt-cache policy`. If it's not available, add the repository.
Closes #896
=> Add support for Debian 13

rocketpool/watchtower/finalize-pdao-proposals.go
remove redundant word in comment
=> chore: remove redundant word in comment

rocketpool-cli/service/service.go
=> Add NethermindPruneFreeSpaceRequired

shared/services/rewards/utils.go, shared/services/rocketpool/client.go
Optimize code using a more modern writing style which can make the code more efficient and cleaner.
=> refactor: replace Split in loops with more efficient SplitSeq
