rocket-pool/smartnode

rocketpool-cli/node/commands.go
rocketpool-cli/node/deposit.go
rocketpool/api/network/node-fee.go
shared/types/api/network.go

Add command line options for the `rocketpool node deposit` command.  Help message looks like:
```
NAME:
rocketpool node deposit - Make a deposit and create a minipool
USAGE:
rocketpool node deposit [options]
OPTIONS:
--amount value, -n value  Amount of ETH to deposit (0|16|32) (default: 0)
--autofee, -a             Use the suggested fee rate
--fee value, -f value     Minimum node commission rate in % [0-20] (default: 0)
```
**Implementation notes:**
These command line options allows non-interactive entry to this command.  Error handling and range checks are from existing logic for interactive input.  the `--autofee` option will override the `--fee` option if they are set together.

Issue #60 command line options for deposit

---

rocketpool/node/stake-prelaunch-minipools.go
shared/services/config/config.go
shared/services/rocketpool/client.go

The following parameters are added in `config.yml` and `settings.yml`:
- `smartnode`
- `projectName`
- `networkName`
- `image`
- `chain`
- `volumeName`
These fields replace corresponding docker variable names to enable multiple and different configurations of rocketpool to run on the same host machine.
For example, these parameters can be used to run and test a different versions of Rocketpool, Eth1 node, Eth2 node or validators before switching over completely.  This would be a useful feature to have on mainnet to minimise downtime.

Parameterize docker variables

---

rocketpool-cli/minipool/status.go
rocketpool-cli/node/status.go
rocketpool/api/minipool/utils.go
shared/types/api/minipool.go

Fixes rocket-pool/smartnode#82
- Add number of blocks until withdrawal is available to minipool status
- Ability to show short blurb with each minipool status print
Example minipool status print out:
```
API server listening at: 127.0.0.1:37587
2 Withdrawable minipool(s):
(Exited state - withdraw may not be available until after delay)
-----------------
Address:           0x00000000000000000000000000000000000000001
Status updated:    2021-01-27, 05:53 +0000 UTC
Node fee:          9.999991%
Node deposit:      16.000000 ETH
Final balance:     32.364214 ETH
Withdrawal available in: 53096 blocks
-----------------
Address:           0x00000000000000000000000000000000000000002
Status updated:    2021-01-27, 06:00 +0000 UTC
Node fee:          20.000000%
Node deposit:      16.000000 ETH
Final …
```

clarify withdrawable minipool status

---

shared/services/beacon/lighthouse/client.go
shared/services/beacon/prysm/client.go

Fixes rocket-pool/smartnode#80
- Prysm api response to ListValidators and ListValidatorBalances returns paged responses, so we need to make multiple requests with supplied NextPageToken until there are no more pages
- Make Lighthouse validator requests in batches as well and not iterate through the entire set of validators

Fix Prysm watchtower network balance

---

rocketpool/node/stake-prelaunch-minipools.go
shared/services/config/config.go
shared/services/rocketpool/client.go
shared/services/services.go

Fixes rocket-pool/smartnode#86 
- detect whether we are running inside a container
- if we are in docker then proceed to restart container as usual
- if we are not in docker then execute the configured command

Restart validator service on non-docker setup

---

shared/services/config/config.go
shared/services/rocketpool/client.go

This is a partner to https://github.com/rocket-pool/smartnode-install/pull/39 - it just adds a `graffitiVersion` to `config.yml` which replaces the old `ROCKET_POOL_VERSION` in `start-validator.sh` so it's easier to update and propagate to various files.

Added config support for graffitiVersion

---

rocketpool-pow-proxy/proxy/ws-proxy.go
rocketpool-pow-proxy/rocketpool-pow-proxy.go

This is part of a series that fixes #137. It modifies the PoW proxy to support separate arguments for the HTTP and Websocket addresses.

Fix the PoW-Proxy for custom eth1 clients

---

rocketpool-cli/node/deposit.go
rocketpool/api/node/deposit.go
shared/services/gas.go
shared/services/rocketpool/gas.go
shared/types/api/node.go

This PR is same as #98 but merged to https://github.com/rocket-pool/smartnode/tree/beta-3
Example output from `rocketpool node deposit`
```
Please choose an amount of ETH to deposit:
1: 32 ETH (minipool begins staking immediately)
2: 16 ETH (minipool begins staking after ETH is assigned)
2
The current network node commission rate that your minipool should receive is 20.000000%.
The suggested maximum commission rate slippage for your deposit transaction is 1.000000%.
This will result in your minipool receiving a minimum possible commission rate of 19.000000%.
Do you want to use the suggested maximum commission rate slippage? [y/n]
y
Estimate gas price: 1.000000 Gwei, Estimate gas: 1394257, Estimate gas cost: 0.001394 ETH
Are you sure you want to deposit 16.000000 ETH to create a minipool …
```

estimate gas cost before proceeding - tokenomics

---

shared/services/rocketpool/odao.go

Error messages from API calls were not formatted with the correct variable.
```
nii236 at ethstaker in ~ 
$ rocketpool odao member-settings
Could not get oracle DAO member settings: %!w(<nil>)
```
This pull request changes the `fmt.Errorf` from using `err`, which is the error from the HTTP client, to `Response.Error` which is the error message from the HTTP response.

Change formatted API error response to use API response instead of a nil error

---

rocketpool-cli/rocketpool-cli.go
rocketpool-cli/wallet/commands.go
rocketpool-cli/wallet/export.go
rocketpool-cli/wallet/init.go
shared/utils/cli/prompt.go

Closes #167 
Y'all have some interesting code style for golang
NB- the printing is to stderr. Two things: urfave cli should default to stderr but appears to be printing to stdout. I can't figure out why. It does provide a package-level override, and it's possible some other import is overriding it. Additionally, most of the error reporting in this project appears to print to stdout. This is fine for most use cases, but since `wallet export` intuitively will be redirected to a regular file, the errors should be printed to stderr. This avoids situations where the regular file is created, but contains an error message, and the user thinks they have successfully exported the wallet when they actually have not.
I also noticed that when the app exits with an error, it has exit code 0. Not …

Prompt for user input before printing sensitive data in wallet exports

---

rocketpool-cli/service/config.go
rocketpool-cli/service/service.go

1- random client selection allows supermajority clients, even when
includeSupermajority is false.
2- one ignored Error
The random selection is a bit more complex now. I didn't want to open the possibility of an infinite loop if both `Fallback == true` and `includeSupermajority == false` and no clients fit the criteria. Instead, the loop iterates the client list once, collecting eligible clients into a slice, and erroring if resulting vector is empty. Otherwise, it randomly picks a client from the new slice.
N.B. This is untested, as I'm not currently set up on prater

Fix a couple staticcheck revealed issues

---

shared/services/rocketpool/client.go
shared/services/rocketpool/command.go

Fix for the `Error piping stdout: read |0: file already closed` bug.
From the [docs](https://pkg.go.dev/os/exec#Cmd.StderrPipe): 
> ... it is incorrect to use Run when using StderrPipe.
I tested it with a few of the standard commands and it appears to work as expected. I did not test with the SSH method. I see that has been marked as deprecated. I've never used it before, so I don't have that set up.
A kind note: It was really painful to contribute this change because `gofmt` is not being used for this project and I almost did not make a contribution because it was not used - knowing that my git stage would be a big mess. Please consider running `go fmt` over the code base. It is a standard in the industry. It will lower the barrier to entry for new contributes who have all their standard …

Use Start/Wait instead of Run to handle stdin/stdout better

---

shared/services/rocketpool/client.go

Nimbus's extip field will silently accept ipv6, but per the nimbus team, it is not currently supported.
From the `net` docs:
> To4 converts the IPv4 address ip to a 4-byte representation. If ip is not an IPv4 address, To4 returns nil.

Print a warning when the externalip library returns ipv6

---

rocketpool-cli/service/service.go

This may be too aggressively DRY (ie, the readability trade-off might not be worth it?)

DRY out the rocketpool service version string formatting code, and fix a copy paste victim

---

rocketpool-cli/service/commands.go
rocketpool-cli/service/service.go
shared/services/rocketpool/client.go

Since v1.3.0 allows users to make `override` files, I wanted to have an easy way to debug these.
This PR adds the output of `docker-compose config` to the `rocketpool service compose` command.
For example my custom network and port mapping in `override/node.yml`:
```
version: "3.7"
services:
node:
x-rp-comment: Add your customizations below this line
environment:
- ENABLE_METRICS=true
ports:
- "127.0.0.1:9102:9102"
networks:
net:
external: true
name: openethereum_ethereum
```
Can now be found by using:
```
rpl@rplhost:~$ rocketpool service compose
networks:
net:
external: true
name: openethereum_ethereum
services:
<snip>
node:
cap_add:
- dac_override
cap_drop:
- all
command: -m 0.0.0.0 -r 9102 node
container_name: rocketpool_node
environment:
ENABLE_METRICS: "true"
image: …
```

Added 'service compose' command to print docker-compose config

---

rocketpool-cli/wallet/bip39/mnemonic-validator.go
rocketpool-cli/wallet/utils.go

Addresses https://github.com/rocket-pool/smartnode/issues/200
Tested on `wallet init` `wallet recover` and `wallet test-menmonic`

Update mnemonic user input flow to be word-at-a-time and tolerant of partial words (minimum 4 letters)

---

go.mod
go.sum
shared/services/rocketpool/client.go

In `#support`, we're seeing node operators with two distinct, but related issues:
* Bad peering with Nimbus/Besu. This is because on dual-stack (IPv4 and IPv6) nodes, the external IP detection code sometimes finds the IPv4, other times the IPv6. Using IPv6 is not ideal, and will cause peering / network issues.
* Mysterious container restarts. For example, sometimes a user will update the docker image tag for Grafana or a consensus client. When starting the rocketpool service (e.g. `rocketpool s s`) the `rocketpool_eth1` container will unexpectedly be recreated. We've managed to track this down to the same issue: the external IP detection code switching between IPv4 and IPv6. Every time it changes, the containers will be recreated and restarted.
A potential solution is, when discovering …

Prefer external IPv4 discovery

---

README.md
rocketpool-cli/node/commands.go
rocketpool-cli/node/sign-message.go
rocketpool/api/node/commands.go
rocketpool/api/node/sign-message.go
shared/services/rocketpool/node.go
shared/services/wallet/wallet.go

Adding option to sign an arbitrary message using the node's private key. (EIP-191 personal_sign)
Prints the result in a format that can be directly used on beaconcha.in, but could also be used to sign messages for other use cases.

764 - Adding option to sign an arbitrary message.

---

rocketpool-cli/service/service.go
shared/services/rocketpool/client.go
shared/utils/rp/config.go

Uses the flag added in https://github.com/rocket-pool/smartnode-install/pull/74
I believe the logic reordering is safe- the LoadConfig call doesn't seem to have side-effects, and I don't _think_ it will cause errors when run on a fresh install, but I haven't tested it.

Pass DataPath to install script for upgrades

---

README.md

this PR removes outdated ETH 2.0 language (referencing the anticipated merge in 2020) and adds missing cli commands.

Update `eth 2.0` language and add missing cli commands

---

rocketpool-cli/node/deposit.go
rocketpool/api/node/commands.go
rocketpool/api/node/deposit.go
rocketpool/watchtower/submit-rpl-price.go
shared/services/rocketpool/node.go

If the transaction is not sent, its RLP encoding is printed out instead.
Depends on https://github.com/rocket-pool/rocketpool-go/pull/10.

Make daemon sending deposit transaction optional

---

rocketpool-cli/network/dao-proposals.go
shared/types/api/node.go

Snapshot Choice has a type "Any", so it needs to be treated as an interface{} in Go.
To parse and show results, so far I've seen that interface can be either float64, []interface{} (which is actually []float64), or a map[string] interface{} (which becomes map[string] float64). All these cases should work correctly now.
Fix #265

Adapt snapshot struct to receive a response of type "Any"

---

rocketpool/api/node/smoothing-pool.go
rocketpool/api/node/voting.go
rocketpool/node/collectors/beacon-collector.go
rocketpool/node/collectors/node-collector.go
rocketpool/node/collectors/rpl-collector.go
rocketpool/node/collectors/smoothing-pool-collector.go
rocketpool/node/collectors/snapshot-collector.go
rocketpool/node/metrics-exporter.go
shared/services/ec-manager.go
shared/services/rocketpool/smoothing-pool.go
shared/types/api/node.go

Adding the following metrics:
- Active Snapshot proposals
- Closed Snapshot proposals
- Votes from user/delegate on active Snapshot proposals
- Votes from user/delegate on closed Snapshot proposals
- ETH balance on the smoothing pool contract
- Claimed ETH from the smoothing pool rewards
- Unclaimed ETH available from the smoothing pool rewards
Closes #259

Add prometheus metrics

---

shared/services/config/teku-config.go

Changing the default value to false for the "Enable Teku Archive Mode" option.
Reasoning: It is only needed for tree generation, which most users don't need to do. I'm also helping lots of users who were complaining about disk space for using the archive mode.

Teku Archive Mode default to false

---

rocketpool-cli/node/utils.go

#249 
Get request seems to fail on the current "https://freegeoip.app/json/" due to missing an API key.
Proposing solution to change from "https://freegeoip.app/json/" to a working API "https://ipinfo.io/json" which is public without requiring an API key.
Although this does not fulfil the second criteria, it should fix the majority of first-pass time zone location string issues.

Changed API to a working one for IP geolocation

---

shared/services/wallet/validator.go

Fix the next_account value after recovering keys (should be walletIndex + 1).
Closes #290

Fix the nextAccount value after recovering keys.

---

rocketpool-cli/service/config/step-external-prysm.go
shared/services/config/external-configs.go

Can't change the config key name easily, due to migration issues.
Also trim the `http://` prefix as it is explicitly verboten

Prysm has renamed their JSON-RPC API to gRPC, so we should use the new language in the TUI

---

rocketpool/api/node/sign-message.go
shared/services/rocketpool/node.go

The rescue node will use a signed message to identify the user requesting access has a Rocket Pool node and will require a signed message from the node wallet.
Currently, the signMessage function is checking the client sync state. This is a problem as users of the rescue node would not always have synced clients.
Closes #295

Ignore sync check when signing messages.

---

shared/services/rocketpool/client.go
shared/services/rocketpool/command.go

Hopefully this is the last time we do this lol.
The problem with `io.Copy` is that when the `cmd` is not given an `io.Writer` to write to, it will create it's own, and it will close this when it exits, and the `Read` function does not like this.
So in this case, the proper thing to do is to give it an `io.Writer` to write to, and we can use `os.Stdout/err` for this. When we set the writers, the `cmd` does not not close them on exit, which is what we want in the case for `os.Stdout/err`.

Fix subprocess writing to stdout/err

---

rocketpool-cli/service/config/main-display.go

Fixes a bug where if you start the config wizard with a small terminal, and you get the message that the terminal is too small, and then you maximize the terminal, it won't redraw, so you have to Ctrl+C and run the configuration again.
Using `BeforeDraw`, fixes this problem because it's deciding to render the "too small" message or wizard when the terminal has been resized, so you don't need to trigger another render to get this to update.

Fix terminal resize

---

rocketpool-cli/service/config/step-checkpoint-sync.go

Seems like the url in the docs have been updated to:
https://docs.rocketpool.net/guides/node/config-docker.html#beacon-chain-checkpoint-syncing
Not sure if there's already a duplicate commit, please feel free to close if so.

chore: update url for checkpoint sync docs

---

rocketpool-cli/node/utils.go
rocketpool-cli/wallet/utils.go
rocketpool/api/node/voting.go
rocketpool/node/node.go
rocketpool/watchtower/generate-rewards-tree.go
rocketpool/watchtower/process-penalties.go
rocketpool/watchtower/submit-rewards-tree.go
shared/services/beacon/client/std-http-client.go
shared/services/config/config-legacy.go
shared/services/config/rocket-pool-config.go
shared/services/gas/etherchain/etherchain.go
shared/services/gas/etherscan/etherscan.go
shared/services/passwords/manager.go
shared/services/rewards/manager.go
shared/services/rocketpool/client.go
shared/services/rocketpool/fee-recipient.go
shared/services/rocketpool/legacy-client.go
shared/services/wallet/keystore/lighthouse/keystore.go
shared/services/wallet/keystore/nimbus/keystore.go
shared/services/wallet/keystore/prysm/keystore.go
shared/services/wallet/keystore/teku/keystore.go
shared/services/wallet/wallet.go
shared/utils/rp/config.go
shared/utils/wallet/recover-keys.go

Applied the following changes:
* `ioutil.WriteFile` -> `os.WriteFile` ([docs](https://pkg.go.dev/io/ioutil#WriteFile))
* `ioutil.ReadFile` -> `os.ReadFile` ([docs](https://pkg.go.dev/io/ioutil#ReadFile))
* `ioutil.ReadAll` -> `io.ReadAll` ([docs](https://pkg.go.dev/io/ioutil#ReadAll))
These are all no-op changes since the deprecated methods were calling the underlying `os` and `io` methods.
Fixing deprecated `ioutil.ReadDir` is slightly more involved, so did not address that one in this PR.

Fix deprecated ioutil file methods

---

rocketpool-cli/minipool/exit.go
shared/utils/cli/prompt.go

NOs will need to type a "I agree" instead of 'y' on important commands like `rp m e`. 
This would avoid a quick 'y' answer when a user thought they were using another command.
Closes #329

Require user to type 'I agree' to exit minipools.

---

shared/services/rewards/generator-impl-v5.go

Without this little line we run the risk of including odao members added after the interval ends:
```go
oDaoAddresses, err := trustednode.GetMemberAddresses(r.rp, r.opts)
if err != nil {
return err
}
```
or, using the wrong sp contract if it was updated tightly after the interval ends:
```go
// Get the Smoothing Pool contract's balance
smoothingPoolContract, err := r.rp.GetContract("rocketSmoothingPool", r.opts)
```
or, using an illegal network
```go
// Validates that the provided network is legal
func (r *treeGeneratorImpl_v5) validateNetwork(network uint64) (bool, error) {
valid, exists := r.validNetworkCache[network]
if !exists {
var err error
valid, err = tnsettings.GetNetworkEnabled(r.rp, big.NewInt(int64(network)), r.opts)
if err != nil {
return false, err
} …
```

Set treegen v5 r.opts

---

rocketpool-cli/wallet/utils.go
rocketpool/api/service/terminate.go
rocketpool/watchtower/generate-rewards-tree.go
shared/utils/wallet/recover-keys.go

Migrate all `ioutil.ReadDir` -> `os.ReadDir` as recommended per the deprecation note. Note that `os.ReadDir` returns a different struct than the deprecated method. Both structs support `Name()` and `IsDir()` methods, so this should be a drop-in replacement based on a read of the code.

Migrate deprecated `ioutil.ReadDir` method calls

---

shared/services/beacon/client.go
shared/services/beacon/client/std-http-client.go
shared/services/beacon/client/types.go
shared/services/rewards/generator-impl-v1.go
shared/services/rewards/generator-impl-v2.go
shared/services/rewards/generator-impl-v3.go
shared/services/rewards/generator-impl-v4.go
shared/services/rewards/generator-impl-v5.go

* Change []beacon.Committee to an interface to reduce copying on the hot path
* Allow buffered decoding in the BN std-http-client
* Reuse []string buffers for bn committee responses
* Reuse json.Decoder objects (which have internal buffers) across calls to the beacon node's committees endpoint

BN client Committees response optimizations

---

rocketpool-cli/service/config/settings-metrics.go

This enables lodestar beaconcha.in node metrics support, depends on https://github.com/rocket-pool/smartnode-install/pull/93 to work
Related https://github.com/rocket-pool/smartnode/pull/204
Requires Lodestar v1.8.0 (release date 17/18 Apr.)

Enable lodestar beaconcha.in node metrics support

---

shared/services/rocketpool/client.go
shared/utils/rp/config.go

closes https://github.com/rocket-pool/smartnode/issues/401

Prevent truncation of user-settings.yml when disk is full by writing to /tmp first and moving the result to user-settings.yml

---

rocketpool-cli/network/dao-proposals.go
rocketpool-cli/node/status.go
rocketpool-cli/node/sync.go
rocketpool-cli/service/service.go
rocketpool-cli/wallet/status.go
shared/services/config/rocket-pool-config.go
shared/services/rocketpool/client.go
shared/utils/cli/utils.go

We often call `cliutils.PrintNetwork(rp)`, which in turn calls `rp.LoadConfig()`, which then discards the result before it returns. The same functions often proceed to call `rp.LoadConfig()` again.
This isn't ideal for two reasons:
1) If LoadConfig ever has side-effects, it may not be reentrant
2) We parse stuff twice, which isn't slow but it isn't fast either.
Instead we can just add a function on RocketPoolConfig to get the network, and change `cliutils.PrintNetwork` to take that as an argument.

Dedup calls to LoadConfig

---

addons/rescue_node/addon.go
rocketpool-cli/node/status.go

Since many people use Rescue Node to resync eth1 (or change clients), it would be ideal if `rocketpool node status` always printed the Rescue Node details when both the wallet is initialized and the plugin is enabled.
This will conflict with https://github.com/rocket-pool/smartnode/pull/418 so maybe merge that one first and I'll rebase

Print rescue node plugin info even when the EC is syncing

---

shared/services/rewards/generator-impl-v8.go

```
2024/01/10 02:44:48  Calculated rewards:           37457092819124878921189 (error = 1978 wei)
2024/01/10 02:44:48  Total Oracle DAO RPL rewards: 3157097823326239794952 (3157.098)
2024/01/10 02:44:48  Calculated rewards:           3157097823326239794936 (error = 16 wei)
2024/01/10 02:44:48  Actual Protocol DAO rewards:  12895941956298708316972 to account for truncation
2024/01/10 02:44:48  Total Node Weight:            6726637820256974218802831
```

Print total node weight in treegen logs

---

rocketpool/watchtower/generate-rewards-tree.go
rocketpool/watchtower/submit-rewards-tree-rolling.go
rocketpool/watchtower/submit-rewards-tree-stateless.go
shared/services/rewards/cid-calculator.go
shared/services/rewards/files.go
shared/services/rewards/files_test.go
shared/services/rewards/utils.go

Introducing a new interface allows us to abstract the process of writing/reading tree and performance files from disk, as well as compressing the files and calculating their CIDs.
This resolves at least one bug where CIDs are calculated with incorrect filenames.
Read shared/services/rewards/files.go first. This is the new abstraction.
See it in action in the rest of the files. The rules are:
1. When downloading or generating a tree, we call `NewLocalFile` to create the struct, `Write` when we want to write it, `CompressedCid()` to calculate the cid and write the compressed file to disk.
2. When reading a file from disk we use `ReadLocalRewardsFile` or `ReadLocalMinipoolPerformanceFile` which reads the files and parses the bytes in one go. It assumes the file is _not_ compressed, as the …

Add local file abstraction for treegen and fix compression bugs with cid calculation

---

rocketpool-cli/rocketpool-cli.go

Using `os.Arg` on L117 is janky but I accept that we want to parse the config file before calling `app.Run`.
However, once we find the first instance of `-c` or `--config-path`, we should break.
Otherwise, `rocketpool -c ~/.rocketpool wallet init -c` doesn't work, despite:
```
$ rocketpool wallet init --help
NAME:
rocketpool wallet init - Initialize the node wallet
USAGE:
rocketpool wallet init [options]
OPTIONS:
--password value, -p value         The password to secure the wallet with (if not already set)
--confirm-mnemonic, -c             Automatically confirm the mnemonic phrase
--derivation-path value, -d value  Specify the derivation path for the wallet.
Omit this flag (or leave it blank) for the default of "m/44'/60'/0'/0/%d" (where %d is the index).
Set this to "ledgerLive" to use …
```

Fix -c shorthand for subcommands

---

rocketpool/api/minipool/change-withdrawal-creds.go
shared/services/beacon/client/std-http-client.go
shared/services/beacon/client/types.go

Fix the exit signatures as they were failing after the Dencun upgrade on Holesky.
Always using the CAPELLA_FORK_VERSION when computing the domain for the voluntary exit signature.
Domain() function was deprecated so it was replaced by ComputeDomain()

Fix voluntary exit signatures

---

shared/services/rewards/rewards-file-v2.go
shared/services/rewards/rewards-file-v3.go
shared/services/rewards/types.go
shared/services/rewards/utils.go

Main goal is to print a more verbose error message when a rewards file has a version in excess of the binary's maximum- we should just tell the user to update smartnode in the error message rather than having them file into support:
Secondary goal is to improve the parse implementation. Merges the parsing of the header into a single function, adds a function that rangechecks the version.
The package interface is unchanged.

Make rewardsFileVersion type to encapsulate version range checks. Make errors more user friendly

---

shared/services/config/grafana-config.go

There is a known issue reg panel titles not centered (https://github.com/grafana/grafana/issues/73099).
Closes #444

Upgrade Grafana.

---

rocketpool-cli/service/commands.go
rocketpool-cli/service/service.go
shared/services/rocketpool/client.go

This is an implementation for claiming part of bounty BA0902402 ("Patches Delegated Work") which was awarded at https://dao.rocketpool.net/t/round-9-jan-14th-feb-12th-grants-bounties-retrospective-awards-results/2752
Specifically this is an implementation of the new `rocketpool service reset` and `rocketpool service prune` commands as specified in [the bounty application](https://dao.rocketpool.net/t/round-9-gmc-call-for-bounty-applications-deadline-is-february-11/2635/3) under "Feature Request: rocketpool service prune and rocketpool service reset" and corresponding to issue #323 .
~~This is a draft until I add `rocketpool service prune` and resolve a discussion with patches in #323 .~~
NOTE: There is a discussion #323 that we should resolve before merging.
<details>
<summary>Example …

feat: rocketpool service reset for bounty BA0902402 (Patches Delegated Work)

---

rocketpool/node/collectors/node-collector.go
shared/services/rewards/types.go
shared/services/rewards/utils.go
shared/services/state/network-state.go

resolves https://github.com/rocket-pool/smartnode/issues/439. Tested against Patch's (overcollateralized) holesky node. 
Before:
After:

Correct rocketpool_node approximate rpl reward panel for RPIP-30 changes (Milestone A)

---

rocketpool-cli/node/status.go
rocketpool-cli/service/config/settings-alerting.go
rocketpool-cli/service/config/settings-native-home.go
rocketpool/api/node/status.go
shared/services/alerting/alerting.go
shared/services/config/alertmanager-config.go
shared/types/api/node.go

- Adds a new Alertmanger host config that is only used in native mode
- The AlertingConfigPage is was made reusable so it works in both native mode config and docker config
fixes #462
fixes #463
Related to rocket-pool/docs.rocketpool.net#79
Keeping this a draft pending:

fix: support for using alerting in native mode

---

install/install.sh
src/go.mod
src/go.sum
src/rocketpool-cli/rocketpool-cli.go
src/rocketpool-daemon/node/defend-pdao-props.go
src/rocketpool-daemon/node/distribute-minipools.go
src/rocketpool-daemon/node/download-reward-trees.go
src/rocketpool-daemon/node/manage-fee-recipient.go
src/rocketpool-daemon/node/promote-minipools.go
src/rocketpool-daemon/node/reduce-bonds.go
src/rocketpool-daemon/node/stake-prelaunch-minipools.go
src/rocketpool-daemon/node/verify-pdao-props.go
src/rocketpool-daemon/watchtower/cancel-bond-reductions.go
src/rocketpool-daemon/watchtower/check-solo-migrations.go
src/rocketpool-daemon/watchtower/dissolve-timed-out-minipools.go
src/rocketpool-daemon/watchtower/finalize-pdao-proposals.go
src/rocketpool-daemon/watchtower/generate-rewards-tree.go
src/rocketpool-daemon/watchtower/metrics-exporter.go
src/rocketpool-daemon/watchtower/respond-challenges.go
src/rocketpool-daemon/watchtower/submit-network-balances.go
src/rocketpool-daemon/watchtower/submit-rewards-tree-rolling.go
src/rocketpool-daemon/watchtower/submit-rewards-tree-stateless.go
src/rocketpool-daemon/watchtower/submit-rpl-price.go
src/rocketpool-daemon/watchtower/submit-scrub-minipools.go

As per Patches, we'll start treating `v2` like `master` and only put things into it via PRs instead of committing directly.

Move dev into v2

---

rocketpool-cli/pdao/commands.go

old: 
```
deposit-fee, df                                    Propose updating the deposit.fee setting; specify a percentage between 0 and 1 (e.g., '0.51' for 51%)
```
new:
```
deposit-fee, df                                    Propose updating the deposit.fee setting; specify a percentage between 0 and 0.01 (e.g., '0.001' for 0.10%)
```

fixed tooltip to accurately represent guardrails

---

rocketpool/node/collectors/node-collector.go

0xfornax saw a mainnet node that had momentary periods of rocketpool_node_sync_progress{client="beacon"} slightly less than zero (e.g. 0.9999998854537224) and it was triggering the alert. Yet `rocketpool node sync` reported the client was synced. This is a somewhat speculative fix to potentially prevent that.
@0xfornax Wonder if this might help out in your case. The [Beacon API docs](https://ethereum.github.io/beacon-APIs/#/Node/getSyncingStatus) aren't explicit but they imply that progress is only valid if is_syncing is false. I saw somewhere else that the node was forcing progress to 1 when syncing=false.

fix: when bc status is not syncing fix progress to 1.0

---

src/shared/config/migration/migration-manager.go
src/shared/config/smartnode-config.go

`UpdateConfig` needs to actually return the updated config so it can be used by the upstream caller.
`configVersionString` was being clobbered.

Fix a few bugs with the migration

---

.gitignore
build.sh
docker/daemon-build.dockerfile
docker/daemon.dockerfile

1. Removes the requirement that build.sh must be run from the project's parent dir
2. Ignores build/ subtree
3. Cleans up artifact naming a bit to reduce complexity of build docker files and remove a bunch of `mv` from the script
4. Only pushes to docker hub if `-u` is passed. (allows for local development with the 'official' build pipeline artifacts)

Refactor build.sh a bit

---

rocketpool-cli/service/service.go

Adds a friendly message suggesting that users should resync geth with PBSS enabled instead of pruning it.
Deletes two redundant color defines

Push users towards pbss

---

docker/rocketpool-dockerfile

Provides parity with smartnode-builder which was bumped in support of go 1.21
Without this, the rocketpool container attempts to run a binary built in bookworm with a bullseye base container, which has a different version of GLIBC

Bump debian version used for rocketpool container image to bookworm

---

rocketpool-cli/minipool/close.go

Basically, when a vacant minipool is scrubbed, it probably has a non-0 refund, but a 0 user-deposit.
That means its `distributableBalance` is actually negative in this code block... but we still want to let it be closed.
close() will wipe out the refund.

Allow scrubbed/dissolved minipools with refunds to be closed

---

rocketpool/api/node/set-stake-rpl-for-allowed.go
rocketpool/watchtower/submit-network-balances.go
rocketpool/watchtower/submit-rpl-price.go
rocketpool/watchtower/utils/utils.go
rocketpool/watchtower/utils/utils_test.go
shared/services/config/smartnode-config.go
shared/services/rewards/types.go
shared/services/rocketpool/network.go
shared/types/config/types.go

This PR refactors prices and balances submissions previously based on locating event submissions to define the next submission time. The code now introduced a new TUI parameter that will be used to calculate when the next submission is due.
The default value for the new parameter is 1713420000 (April 18, 2024 6:00:00 AM UTC). Considering the 24-hour submission interval (on mainnet), after the Houston launch, oDAO nodes would submit new prices/balances every day for the block at 6:00:00 AM UTC (or, in case of a missed slot, the last proposed block before this time). This makes the submission process in a predictable way, as mandate by RPIP-35, and gets rid of event issues, especially during the transition to Houston.

Using a TUI timestamp parameter for prices/balances submissions

---

sszgen.sh

sszgen.sh used to generate a file that is now part of NMC, so it should be removed from smartnode.
Counterpart: https://github.com/rocket-pool/node-manager-core/pull/3

Remove sszgen.sh

---

rocketpool-cli/pdao/invite-sc.go
rocketpool-cli/pdao/kick-sc.go
rocketpool-cli/pdao/one-time-spend.go
rocketpool-cli/pdao/percentages.go
rocketpool-cli/pdao/propose-settings.go
rocketpool-cli/pdao/recurring-spend-update.go
rocketpool-cli/pdao/recurring-spend.go
rocketpool-cli/pdao/replace-sc.go
rocketpool/api/pdao/invite-security.go
rocketpool/api/pdao/kick-security.go
rocketpool/api/pdao/one-time-spend.go
rocketpool/api/pdao/percentages.go
rocketpool/api/pdao/propose-settings.go
rocketpool/api/pdao/recurring-spend.go
rocketpool/api/pdao/replace-security.go
rocketpool/api/pdao/update-recurring-spend.go
shared/types/api/pdao.go

PDAO functions edited:
- Propose Setting
- Propose Sec Council Invite
- Propose Sec Council Kick 
- Propose One Time Spend
- Propose Rewards Percentages
- Propose Recurring Spend
- Propose Recurring Spend Update
- Propose Sec Council Update
~~Haven't tested these 3 yet:~~
~~- Propose Sec Council Kick~~
~~- Propose Recurring Spend Update~~
~~- Propose Sec Council Update~~
fixed usage of goroutines per Fornax's suggestion!

Added "is RPL Locking Allowed" check to every `PDAOCanProposeXYZ` function 

---

.github/workflows/lint.yml
go.mod
go.sum
rocketpool-cli/commands/minipool/vanity.go
rocketpool-cli/commands/service/config.go
rocketpool-cli/commands/service/start.go
rocketpool-daemon/api/node/status.go
rocketpool-daemon/common/alerting/alerting.go
rocketpool-daemon/common/rewards/generator-impl-v8.go
rocketpool-daemon/common/rewards/utils.go
rocketpool-daemon/common/services/requirements.go
rocketpool-daemon/common/validator/validator-manager.go
rocketpool-daemon/node/distribute-minipools.go
rocketpool-daemon/node/manage-fee-recipient.go
rocketpool-daemon/node/metrics-exporter.go
rocketpool-daemon/node/node.go
rocketpool-daemon/node/promote-minipools.go
rocketpool-daemon/node/reduce-bonds.go
rocketpool-daemon/node/stake-prelaunch-minipools.go
rocketpool-daemon/rocketpool-daemon.go
rocketpool-daemon/watchtower/submit-rewards-tree-rolling.go
rocketpool-daemon/watchtower/submit-scrub-minipools.go
shared/keys/keys.go

The `alerting` package previously was stateless and simply recreated state every time any alert was called.
Now it is stateful, and only checks config on init(). Logging is done through a logger instead of through stdout.
Fixes `errcheck` issues and uses newest `rocketpool-go/v2` and `node-manager-core` commits which resolve upstream errcheck issues.
Enables all linters :tada:

Make alerting package stateful and directly error-logging. Fix the rest of the unchecked errors.

---

rocketpool-cli/service/service.go

When enabling alerting in the TUI but not enabling Metrics, the following error would occur starting smartnode:
```sh
$ ./rp-run.sh s start
Validator client [lodestar] was previously used - no slashing prevention delay necessary.
[+] Running 8/8
✔ Container rocketpool_alertmanager  Created                                                                                                             0.0s 
✔ Container rocketpool_addon_gww     Started                                                                                                             0.0s 
✔ Container rocketpool_watchtower    Started                                                                                                             0.0s 
✔ Container rocketpool_eth2          Started …
```

fix: An error would occur starting the smartnode when alerting was enabled but metrics was not

---

rocketpool-cli/pdao/get-voting-power.go
rocketpool/api/pdao/get-voting-power.go
shared/types/api/pdao.go

Implemented some suggestions Joe pointed out this morning:
- pdao `BlockNumber` response should be `uint32`
- populated response on L70
- added color to the heading to be consistent with other status menus.

Fix data type and heading color

---

rocketpool-cli/node/status.go
rocketpool-cli/pdao/get-voting-power.go

Nodes that registered pre-houston and haven't initialized voting default to `0x0000000000000000000000000000000000000000` as their delegate, which causes `rp n s` to display the wrong information. 
Before
```
=== Onchain Voting ===
The node has NOT been initialized for onchain voting. You need to run `rocketpool pdao initialize-voting` to participate in onchain votes.
The node has a voting delegate of 0x0000000000000000000000000000000000000000 which can represent it when voting on Rocket Pool onchain governance proposals.
The node is NOT allowed to lock RPL to create governance proposals/challenges.
```
After
```
=== Onchain Voting ===
The node has NOT been initialized for onchain voting. You need to run `rocketpool pdao initialize-voting` to participate in onchain votes.
The node doesn't …
```

Add check for nodes that registered pre-houston to onchain voting status.

---

.github/workflows/changelog.yml

Automatically generates changelog based on commit history. Initiated when a new tag is created, so will update existing CHANGELOG.md when a new tag is created and add commit history since last tag. 
Information it includes is based on if the commits follow good commit convention (feat: , fix: , chore: , etc.). Drastically reduce work needed to maintain changelog going forward.
Closes #510

feat: changelog auto-generation github workflow

---

shared/config/mev-boost-config.go

Adding a missing parameter on the mev-boost configuration.

Add missing param.

---

rocketpool-cli/auction/claim-lot.go
rocketpool-cli/auction/recover-lot.go
rocketpool-cli/minipool/delegate.go
rocketpool-cli/minipool/dissolve.go
rocketpool-cli/minipool/refund.go
rocketpool-cli/minipool/stake.go
rocketpool-cli/odao/execute-proposal.go
shared/services/gas/gas.go

This is a less-than-optimal but quick solution to https://github.com/rocket-pool/smartnode/issues/194
Optimally, the Client struct should be made less stateful. Users of the client interface should be required to pass the gas settings in at time of invocation, providing a compile-time enforcement that the settings are correctly derived.
I have only minimally tested this code.

Re-set the gas settings for iterated client calls, fixing a bug with several activation paths

---

rocketpool-cli/node/status.go

before:
```
The node has a total stake of 768.048780 RPL and an effective stake of 606.056977 RPL.
This is currently 25.35% of its borrowed ETH and 76.04% of its bonded ETH.
It must keep at least 303.028488 RPL staked to claim RPL rewards (10% of borrowed ETH).
RPIP-30 is in effect and the node will gradually earn rewards in amounts above the previous limit of 606.056977 RPL (150% of bonded ETH). Read more at https://github.com/rocket-pool/RPIPs/blob/main/RPIPs/RPIP-30.md
```
after: 
```
The node has a total stake of 768.048780 RPL.
This is currently 25.35% of its borrowed ETH and 76.04% of its bonded ETH.
It must keep at least 303.028488 RPL staked to claim RPL rewards (10% of borrowed ETH).
RPIP-30 is in effect and the node will gradually earn rewards in amounts above the previous limit …
```

Update status menu for RPIP-30 withdrawal down to 60% bonded eth

---

rocketpool-cli/pdao/commands.go
rocketpool-cli/pdao/initialize-voting-with-delegate.go
rocketpool-cli/pdao/initialize-voting.go
rocketpool/api/pdao/commands.go
rocketpool/api/pdao/initialize-voting-with-delegate.go
rocketpool/api/pdao/initialize-voting.go
shared/services/rocketpool/pdao.go
shared/types/api/pdao.go

```
USAGE:
rocketpool pdao command [command options] [arguments...]
COMMANDS:
initialize-voting, iv                 Unlocks a node operator's voting power (only required for node operators who registered before governance structure was in place)
initialize-voting-with-delegate, ivd  Unlocks a node operator's voting power and sets the delegate (saves some gas by initializing and setting the delegate in one transaction)
```
Added two seperate commands (one for initializing voting, another for initializing voting and setting the delegate in one transaction).

Refactor initialize-voting to initialize-voting-with-delegate 

---

rocketpool-cli/pdao/status.go
rocketpool/api/pdao/status.go
shared/types/api/pdao.go

- Fix "address is not in the RP node set" (when voting isn't initialized and you call `rp p s`). This causes the call to return instead of printing the rest of the menu.
```
ubuntu@v1stable:~$ rocketpool p s
error after requesting get-voting-power: address 0xa6073aEecB94FB769bB1b3754A0ef8b3bec36199 is not in the RP node set
```
- Add wallet not initialized check
- Add display for selected network
before:
```
tpan@tpan-meerkat:~$ rocketpool p s
error after requesting get-voting-power: Wallet is not initialized
```
after:
```
tpan@tpan-meerkat:~$ rocketpool p s
Your Smart Node is currently using the Holesky Test Network.
The node wallet is not initialized.
```
Also included some small changes to the `pdao status` menu output (e.g missing newlines)

Handle not in rp nodeset bug

---

rocketpool-cli/node/status.go
rocketpool-cli/pdao/status.go
rocketpool/api/node/status.go
rocketpool/api/pdao/status.go
shared/types/api/node.go
shared/types/api/pdao.go

With a signalling address set: 
```
=== Signalling on Snapshot ===
The node has a voting delegate of 0xcaB549EdE082592D10FE6a238e7e8914aD3a074d which can represent it when voting on Rocket Pool Snapshot governance proposals.
Rocket Pool has no Snapshot governance proposals being voted on.
```
Without a signalling address set: 
```
=== Signalling on Snapshot ===
The node does not currently have a snapshot signalling address set
Rocket Pool has no Snapshot governance proposals being voted on.
```
~TO-DO refine the message for when snapshot signalling is not set~

Refactor node and pdao status to reflect new snapshot signalling.

---

go.mod
go.sum

Using the new rocketpool-go version, which should fix issues to create proposals to change settings.

Bump rocketpool-go version

---

rocketpool/api/node/status.go
rocketpool/api/pdao/status.go
shared/services/config/smartnode-config.go
shared/types/api/node.go
shared/types/api/pdao.go

`SnapshotVotingDelegate` is being deprecated in favor of `SignallingAddress`
This goroutine checks if `GetSnapshotDelegationAddress()` exists, adds `SnapshotVotingDelegate` to the response then queries snapshot. 
With this PR, the goroutine checks if `GetRocketSignerRegistryAddress()` exists, then queries snapshot (`SignallingAddress` is already added to the response further up in the file).

Replace snapshot voting delegate with signalling address

---

rocketpool/watchtower/submit-network-balances.go
rocketpool/watchtower/submit-rpl-price.go
rocketpool/watchtower/utils/utils.go
shared/version.go

At some point the Smart Node stopped doing submissions after the prices/balances consensus was reached. This PR restores the desired behavior, allowing oDAO nodes to make submissions after consensus is reached, as a way to monitor their liveness.

Allow submissions after consensus is reached.

---

.github/workflows/commits.yml
CONTRIBUTING.md

Here is my proposal for how we should proceed with formal contribution guidelines. Not much has changed from the status quo, but for the explicit rules around when a PR review ought to be required.
We also name the team roles explicitly, and provide high level guidelines to contributors.

Add CONTRIBUTING.md (Discussion around contribution guidelines)

---

.github/workflows/unit-tests.yml

Unfortunately for security reasons, there's no comments across forks, but this will be the output for team members who make PRs:
Clicking the URL downloads a .zip file with a `go tool` coverage report html file which can be viewed by the author and the reviewers:
There's no coverage enforcement in the actions right now. We can add some later if we get to the point where it's feasible.

Add coverage reports to CI

---

shared/services/config/mev-boost-config.go

Since December 18th 2023, bloXroute Max Profit relay is also censoring OFAC transactions.
This was announced [on Twitter here](https://x.com/bloxroute/status/1736819783520092357) and is now documented [on their website](https://docs.bloxroute.com/apis/mev-solution/mev-relay-for-validators#relay-types):
> Both two relays currently propagate all available transactions/bundles except the ones that interacted with addresses sanctioned by OFAC, and they have the same filtering requirement, although for legacy reasons, bloXroute still maintains the two relay names in parallel.

Mark bloXroute Max Profit relay as censoring.

---

shared/services/config/besu-params.go

Update to new version. There is a change on smartnode-install to remove a deprecated param.

Besu v24.7.0

---

rocketpool-daemon/api/minipool/close.go

Fixes a bug where the close minipool command would iterate over every minipool on a node.

Pass the selected minipool list, instead of every mp

---

shared/services/config/smartnode-config.go

`0x16d468E69Dbb67Fb924a4c61D7D35F81d1B27A3F` adds an additional call to rebase the WRETH token on optimism for the 4626 vault to work properly.

Update optimism oracle price messenger address 

---

rocketpool-cli/commands/commands.go
rocketpool-cli/rocketpool-cli.go
rocketpool-cli/test/cli.go
rocketpool-cli/test/minipool/status_test.go

The test suite is simple still, and only really works for commands that result in a single http request to the daemon.
Merging is blocked by https://github.com/rocket-pool/smartnode/pull/595 and includes those commits, so maybe don't review this PR yet.

Add a test suite for cli commands, tests for `rocketpool minipool status`

---

client/pdao.go
rocketpool-cli/commands/node/status.go
rocketpool-cli/commands/pdao/commands.go
rocketpool-cli/commands/pdao/signalling-address.go
rocketpool-cli/commands/pdao/status.go
rocketpool-daemon/api/pdao/clear-signalling-address.go
rocketpool-daemon/api/pdao/handler.go
rocketpool-daemon/api/pdao/set-signalling-address.go
rocketpool-daemon/api/pdao/status.go
rocketpool-daemon/common/contracts/rocket-signer-registry.go
rocketpool-daemon/common/proposals/proposal-manager.go
rocketpool-daemon/common/services/service-provider.go
shared/config/resources.go
shared/eip712/eip712.go
shared/eip712/eip712_test.go
shared/types/api/pdao.go
shared/types/voting.go
shared/utils/input.go

`rocketpool pdao status`
`rocketpool pdao set-signalling-address`
`rocketpool pdao clear-signalling-address`

Implement pdao status and signalling address commands 

---

rocketpool-cli/commands/node/status.go
rocketpool-daemon/api/node/status.go
shared/types/api/node.go

Some small changes so v2 `node status` has parity with v1
Deprecated:
```
=== DAO Voting ===
The node does not currently have a voting delegate set, which means it can only vote directly on Snapshot proposals (using a hardware wallet with the node mnemonic loaded).
Run `rocketpool n sv <address>` to vote from a different wallet or have a delegate represent you. (See https://delegates.rocketpool.net for options)
Rocket Pool has no Snapshot governance proposals being voted on.
```
New:
```
=== Signalling on Snapshot ===
The node has a signalling address of tptest.eth (0x18eea3fBe5008d6f7a95d963a4BE403E82d35758) which can represent it when voting on Rocket Pool Snapshot governance proposals.
Rocket Pool has no Snapshot governance proposals being voted on.
```
Also added this to the `=== RPL …

Update node status

---

shared/services/config/nethermind-params.go

Addressing https://github.com/rocket-pool/smartnode/issues/597 -- adding support for Nethermind's PruningMaxDegreeOfParallelism parameter.
Also see, https://github.com/rocket-pool/smartnode-install/pull/134 for where this config parameter is used.

Update Nethermind config to support passing the PruningMaxDegreeOfParallelism parameter

---

shared/services/config/nethermind-params.go

L139 in `shared/services/config/nethermind-params.go` expects an int64 
panic introduced in #613 
```
panic: interface conversion: interface {} is int, not int64
goroutine 1 [running]:
github.com/rocket-pool/smartnode/rocketpool-cli/service.createFlagsFromConfigParams({0xff6738, 0xa}, {0xc0005e7770, 0xa, 0xc0005dea00?}, {0xc000581000?, 0xc00058f6f0?, 0xc0005c8640?}, {0xff0fc0, 0x7})
/home/tpan/Dev/smartnode/rocketpool-cli/service/commands.go:40 +0xfc9
github.com/rocket-pool/smartnode/rocketpool-cli/service.RegisterCommands(0xc000182a80, {0xff0a10, 0x7}, {0xc00058f9d0, 0x1, 0x1})
/home/tpan/Dev/smartnode/rocketpool-cli/service/commands.go:94 +0x337
main.main()
/home/tpan/Dev/smartnode/rocketpool-cli/rocketpool-cli.go:119 +0xd91
```

Fix panic in config

---

rocketpool-cli/pdao/initialize-voting.go

Updated the text to:
- provide more context
- prompt users to carefully review and select a choice
```
:~$ rocketpool pdao initialize-voting
Thanks for initializing your voting power!
You have two options:
1. Vote directly (delegate vote power to yourself)
This will allow you to vote on proposals directly,
allowing you to personally shape the direction of the protocol.
2. Delegate your vote
This will delegate your vote power to someone you trust,
giving them the power to vote on your behalf. You will have the option to override.
You can see a list of existing public delegates at https://delegates.rocketpool.net,
however, you can delegate to any node address.
Learn more about how this all works via: https://docs.rocketpool.net/guides/houston/participate#participating-in-on-chain-pdao-propos …
```

Update initialize voting text 

---

client/pdao.go
rocketpool-cli/commands/pdao/commands.go
rocketpool-cli/commands/pdao/initialize-voting.go
rocketpool-daemon/api/pdao/handler.go
rocketpool-daemon/api/pdao/initialize-voting-with-delegate.go
rocketpool-daemon/common/rewards/utils.go

`rp p iv` allows users to choose if they want to specify a delegate while initializing voting: `InitializeVotingWithDelegate(delegate common.Address)`
If not, voting power is initialized to their own node:  `InitializeVoting()`
This PR ports this feature from V1 into V2
Specifying a delegate: 
```
:~$ rp p iv
Would you like to specify a delegate that can vote on your behalf on Protocol DAO proposals? [y/n]
y
Please enter the delegate's address:
0x7ac4C35034D7d175583E9f5876257fBc59E9946E
+============== Suggested Gas Prices ==============+
```
Without specifying a delegate:
```
:~$ rp p iv
Would you like to specify a delegate that can vote on your behalf on Protocol DAO proposals? [y/n]
n
+============== Suggested Gas Prices ==============+
```
This PR mirrors #628 for smartnode V1, …

Update V2 initialize voting to mirror V1 behaviour 

---

rocketpool-cli/commands/minipool/reduce-bond.go
rocketpool-daemon/common/rewards/utils.go

When bond reductions are disabled, `rocketpool minipool reduce-bond` doesn't populate data fields in the API response. This PR addresses #637 by adding a check in the CLI to properly handle the case of bond reductions being disabled.

Added a check to handle bond reductions being disabled

---

install/deploy/templates/eth1.tmpl
install/deploy/templates/eth2.tmpl
install/deploy/templates/mev-boost.tmpl
install/deploy/templates/validator.tmpl
install/install.sh
install/packages/debian/debian/rules
rocketpool-cli/client/compose.go
rocketpool-cli/client/service.go
rocketpool-cli/commands/service/commands.go
rocketpool-cli/commands/service/install-update-tracker.go
rocketpool-cli/commands/service/install.go
rocketpool-daemon/common/rewards/utils.go
v2.md

1) Allow `rocketpool service install -l` to accept a path, ie, `rocketpool service install -l path/to/installer.sh`
2) Fix linter error
3) update paths to be OSX-friendly

Installer changes to support osx

---

rocketpool-daemon/api/node/set-rpl-withdrawal-address.go

Addresses #634 
`rp-cli` segfaults [here](https://github.com/rocket-pool/smartnode/blob/76440160cd8fbbb49927db0b8247dd5e6defce85/rocketpool-cli/commands/node/set-rpl-withdrawal-address.go#L122) because`rp-daemon` never populates `response.Data.RplStake`

Fixed segfault by populating nil pointer

---

rocketpool-daemon/api/minipool/rescue-dissolved-details.go

Fix for this segfault. 
```
~ $ rocketpool m rd
This command will allow you to manually deposit the remaining ETH for any dissolved minipools, activating them so you can exit them and retrieve your minipool's funds.
Please read our guide at https://docs.rocketpool.net/guides/node/rescue-dissolved.html to fully read about the process before continuing.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c4458]
goroutine 1 [running]:
math/big.(*Int).Cmp(0x4040000000000000?, 0x109f874?)
math/big/int.go:381 +0x18
github.com/rocket-pool/smartnode/v2/rocketpool-cli/commands/minipool.rescueDissolved(0xc0005b4ec0)
github.com/rocket-pool/smartnode/v2/rocketpool-cli/commands/minipool/rescue-dissolved.go:77 +0x539 …
```

Populate empty data field

---

rocketpool-daemon/api/odao/proposals.go
rocketpool-daemon/api/security/proposals.go

This PR addresses #635 
**oDAO**
- Issue with the oDAO list saying proposals are pending when they are not
- Issue with the oDAO detail not displaying details of a valid proposal
**Security Council**
- Security council proposal detail is not showing the detail of a proposal
The commands `rp odao proposals details` and `rp security proposals details`  and `rp odao proposals list` should display the correct state now.

V2 Fixed bugs in odao/sec proposals list and details 

---

rocketpool-daemon/api/odao/propose-settings.go

This PR addresses a segfault while creating odao setting proposals: #636
```
2024/09/17 22:10:10 http: panic serving 127.0.0.1:47816: runtime error: invalid memory address or nil pointer dereference
goroutine 218 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x152e1c0?, 0x25b1fb0?})
/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/rocket-pool/node-manager-core/api/server.HandleServerError(0xc00013ba10, {0x1b45470, 0xc0001da2a0}, {0x0, 0x0})
/home/tpan/go/pkg/mod/github.com/rocket-pool/node-manager-core@v0.5.0/api/server/handle-response.go:71 +0x3a
github.com/rocket-pool/node-manager-core/api/server.HandleFailedResponse(0x0?, {0x1b45470?, 0xc0001da2a0?}, 0x1b448d0?, {0x0?, 0x0?}) …
```

V2 Fixed a bug in odao setting/propose

---

rocketpool-daemon/api/node/withdraw-eth.go

This PR addresses a bug in `node withdraw-eth`:
```
~ $ rocketpool n we
Would you like to withdraw the maximum amount of staked ETH (10.000000 ETH)? [y/n]
y
Cannot withdraw staked ETH:
The node's staked ETH balance is insufficient.
```
`c.amount.Cmp(ethBalance) >= 0` causes `data.InsufficientBalance` to evaluate to `true` when the requested withdrawal amount `c.amount` is maxed (e.g equal to to your balance) 
It should be `c.amount.Cmp(ethBalance) > 0` 
Here it is in [V1](https://github.com/rocket-pool/smartnode/blob/master/rocketpool/api/node/withdraw-eth.go#L78)

V2 Corrected balance comparison for eth withdrawal

---

rocketpool/node/auto-init-voting-power.go
rocketpool/node/defend-pdao-props.go
rocketpool/node/distribute-minipools.go
rocketpool/node/node.go
rocketpool/node/promote-minipools.go
rocketpool/node/reduce-bonds.go
rocketpool/node/stake-prelaunch-minipools.go
rocketpool/node/verify-pdao-props.go
rocketpool/watchtower/process-penalties.go

Automatic transactions in the task loop fail when the user-inputted `priorityFee` is greater than the oracle based `maxFee`. This PR addresses this case by setting `priorityFee` to `min(priorityFee, 25% of the oracle based maxFee`) when `priorityFee > maxFee` for transactions in the node task loop. 
For example: automatically initializing vote power, defending pDAO proposals, bond reductions and so on. 
The change is also applied to watchtower task `process-penalties.go`

Handle a case where priorityFee > maxFee in the task loop

---

install/deploy/scripts/start-mev-boost.sh
install/deploy/templates/mev-boost.tmpl

Porting the changes made as part of https://github.com/rocket-pool/smartnode-install/pull/135 to the v2 branch.

Addressing rocket-pool/smartnode#601 on v2 branch

---

rocketpool-cli/commands/node/stake-rpl.go
rocketpool-daemon/api/node/stake-rpl.go
shared/types/api/node.go

This PR fixes a message in stake-rpl that was outdated and hardcoded 
Old:
```
Are you sure you want to stake 543.482558 RPL? You will not be able to unstake this RPL until you exit your validators and close your minipools, or reach over 100% collateral! [y/n]
```
New:
```
Are you sure you want to stake 543.482558 RPL? You will not be able to unstake this RPL until you exit your validators and close your minipools, or reach 1086.965117 staked RPL (60% of bonded eth)! [y/n]
```

V2 fixed outdated and hardcoded value in stake rpl

---

rocketpool-cli/commands/node/deposit.go

`MinNodeFee` and `MaxNodeFee` are stored as `*big.Int`, as oppposed to being stored as `float64` in V1. 
This means we'll need to use `.cmp()` instead of `==` to compare these values.

V2 Fixed comparison of MinNodeFee and MaxNodeFee

---

rocketpool/watchtower/submit-network-balances.go
rocketpool/watchtower/submit-rpl-price.go

Previous code was incorrectly comparing the `targetBlockNumber` with the `lastSubmissionBlock`, while the target block would always be after the last submission.

Fix submission check.

---

rocketpool-cli/client/service.go
rocketpool-cli/commands/service/commands.go
rocketpool-cli/commands/service/stats.go

An issue with `rp service stats` prevents it from exiting when using `ctrl + c`, so it should be deprecated in favor of `docker stats -a`
Ported over from https://github.com/nodeset-org/hyperdrive/pull/151, thanks Joe for sending this over!

V2 Deprecate `service stats`

---

client/network.go
client/pdao.go
rocketpool-cli/commands/node/deposit.go
rocketpool-cli/commands/node/stake-rpl.go
rocketpool-cli/commands/node/utils.go
rocketpool-daemon/api/network/handler.go
rocketpool-daemon/api/network/is-hotfix-deployed.go
rocketpool-daemon/api/pdao/handler.go
rocketpool-daemon/api/pdao/is-voting-initialized.go
rocketpool-daemon/common/state/update-checks.go
shared/types/api/network.go
shared/types/api/pdao.go

Adds the warning to `rp node stake-rpl` and `rp node deposit` 
```
Your voting power hasn't been initialized yet. Please visit https://docs.rocketpool.net/guides/houston/participate#initializing-voting to learn more.
NOTE: by staking RPL, your node will automatically initialize voting power to itself. If you would like to delegate your on-chain voting power, you should run the command `rocketpool pdao initialize-voting` before staking RPL.
Would you like to continue? [y/n]
n
```
`stake-rpl.go` and `deposit.go` only displays this warning after 1.3.1 hotfix has been deployed. This PR requires the following change from `rocketpool-go:tx-refactor` https://github.com/rocket-pool/rocketpool-go/pull/31

V2 stake/deposit warning

---

shared/services/rewards/generator.go

Supercedes https://github.com/rocket-pool/smartnode/pull/673 to fix the same pathological bug, but with more panache. 
Sorting by ruleset version is sensible, since we generally want to use the highest ruleset version that can be used for a given interval.

Fix the tree version iterator

---

rocketpool-daemon/node/applyto_test.go
rocketpool-daemon/node/defend-pdao-props.go
rocketpool-daemon/node/distribute-minipools.go
rocketpool-daemon/node/node.go
rocketpool-daemon/node/promote-minipools.go
rocketpool-daemon/node/reduce-bonds.go
rocketpool-daemon/node/stake-prelaunch-minipools.go
rocketpool-daemon/node/verify-pdao-props.go

Automatic transactions in the task loop fail when the user-inputted priorityFee is greater than the oracle based maxFee. This PR addresses this case by setting priorityFee to min(priorityFee, 25% of the oracle based maxFee) when priorityFee > maxFee for transactions in the node task loop.
This PR slightly differs from #655 because it includes: 
- A new type: `GasSettings` to consolidate related gas fields and a pointer reciever `ApplyTo` to apply the gas settings to `opts *bind.TransactOpts`
- A unit test for `ApplyTo`

V2 Handle a case where priorityFee > maxFee in the task loop

---

rocketpool-cli/rocketpool-cli.go
rocketpool/rocketpool.go

We use [this](https://raw.githubusercontent.com/rocket-pool/rocketpool.net/refs/heads/main/src/utils/console-message.js?token=GHSAT0AAAAAACLW3W4XV7WEWCI5QKEXXQFSZYPMGLQ) on our sites, so the SN should reflect it as well.

V1 Update authors and copyright year

---

rocketpool-cli/node/commands.go
rocketpool-cli/node/create-vacant-minipool.go
rocketpool-cli/node/deposit.go
rocketpool-cli/node/stake-rpl.go
rocketpool-cli/node/status.go
rocketpool-cli/node/utils.go

- Disabled 16ETH minipool options from `deposit`, `stake-rpl` and `create-vacant-minipool`
- Removed CLI `deposit` and `stake-rpl` flags that support 16ETH minipools 
- Temporarily removed the `-y` flag from `deposit` to prevent users from skipping Saturn 0 notice
- Removed irrelevant RPL stake text from `node status`
- Added a call to check if the node is opted into the smoothing pool 
- Added a Saturn 0 message to `deposit`. It includes a note on the new commission structure and a warning if the node is not opted into the smoothing pool

V1 changes for Saturn 0

---

shared/types/api/node.go

The Snapshot API response changed the `snapshot` type.

The snapshot field updated from string -> int64

---

shared/services/beacon/client/std-http-client.go

Skips the validator duties query when there are no validators running.
Closes #690

Skip request when there are no validators

---

rocketpool/api/node/deposit.go

Using `NodeCreditAndBalance` instead of `NodeUsableCreditAndBalance` since we only need 1 ETH on the DP for minipool creation when using credits.

Fix balance check

---

rocketpool-cli/commands/node/commands.go
rocketpool-cli/commands/node/deposit.go
rocketpool-cli/commands/node/stake-rpl.go
rocketpool-cli/commands/node/status.go
rocketpool-daemon/api/network/rpl-price.go
shared/types/api/network.go

This PR includes changes from #681 and #694
In summary: 
- Removed 16ETH options
- Removed some `node status` text that isn't needed in Saturn 0 
- Updated messages and workflow for `node deposit` (Saturn 0 message, smoothing pool check, 8 eth deposit hardcoded, `--a` and `--y` flags still available)
- Removed stale `node stake-rpl` options now that `node.per.minipool.stake.minimum == 0`
- Replaced those options with `5,10, or 15% borrowed ETH as RPL` as well as custom percentage inputs passed within the command or as a CLI flag.

V2 Saturn 0 changes + node `deposit` and `stake-rpl` updates

---

rocketpool-cli/minipool/close.go
rocketpool/api/minipool/close.go
shared/types/api/minipool.go

Houston Hotfix is live, so this requirement should be deprecated.

V1 revert close requirement on 16eth minipools with uninitialized vp 

---

rocketpool/api/pdao/status.go
rocketpool/node/collectors/snapshot-collector.go
rocketpool/node/metrics-exporter.go

Minor change that should have been included in #708: 
Edited `GetSnapshotProposals` and `GetSnapshotVotedProposals` query to exclude proposals before the latest [rocketpool-node-operator-delegate-v8](https://snapshot.org/#/strategy/rocketpool-node-operator-delegate-v8) strategy. This corrects `pdao status` as well as this pane in grafana:

V1 Edit snapshot query to exclude pre-signalling proposals

---

rocketpool-cli/node/status.go
rocketpool/api/minipool/status.go
rocketpool/api/minipool/utils.go
rocketpool/api/node/status.go
shared/types/api/node.go

This PR addresses #705
`node status` now displays the number of minipools with a deposit size of `<16 eth` and a commission of `<10%` when the node is not opted into the smoothing pool

V1 Inform users who are missing out on bonus commission 

---

rocketpool-cli/minipool/commands.go
rocketpool-cli/minipool/delegate.go

Added a flag ` "include-finalized, f"` flag to `minipool delegate-upgrade` because finalized minipools shouldn't be included by default.

V1 Exclude finalized minipools in `delegate-upgrade` unless `include-finalized` flag is used. 

---

rocketpool-cli/minipool/commands.go

This PR adds the `-y` cli flag to `minipool distribute-balance`
Thanks willyfully in discord for reporting this!

Add -y cli flag to minipool distribute-balance

---

rocketpool-cli/pdao/proposals.go
rocketpool-cli/pdao/vote-proposal.go
rocketpool/api/pdao/proposals.go
shared/types/api/pdao.go

This PR adds a new field `DelegateVoteDirection` to the `PDAOProposalWithNodeVoteDirection`api reponse, then uses it to show the delegate vote direction when querying details for a proposal, or when voting on a proposal. 
```
:~$ rocketpool pdao proposals details 50
Proposal ID:            50
Message:                one-time spend for invoice test-delegate-vote-direction-2
...
...
Node has voted:         no
Delegate has voted:     In Favor
Current Delegate:       0xd48a411E40624A4504e48390419d01A47a50fbFE
```
```
:~$ rocketpool pdao proposals vote 
Please select a proposal to vote on:
1: proposal 50 (message: 'one-time spend for invoice test-delegate-vote-direction-2', payload: proposalTreasuryOneTimeSpend(test-delegate-vote-direction-2,0xE8325F5f4486c2FF2AC7B522Fbc9eB249d46C936,1000000000 …
```

Show delegate vote direction in pDAO proposal details and voting. 

---

rocketpool/watchtower/utils/utils.go

Use the built-in max/min from the standard library in Go 1.21 to simplify the code.

refactor: use the built-in max/min to simplify the code

---

rocketpool/watchtower/constants.go
rocketpool/watchtower/submit-rpl-price.go

This PR makes the RPL price submission work as a health check for oDAO nodes. If a node didn't participate in the previous round, they're going to use that past block as the submission target.

Use the last submission block as target if the node didn't participate in consensus

---

shared/services/rocketpool/client.go

https://go.dev/play/p/WbgPaKbHJdE demonstrates the need/safety of shellescape
Basically, we want to delete the getEscalationCmd to make sure that when root is required, it is used 'correctly'.
'Correctly' here means in a statement that looks like `sudo bash -c 'rm -rf .rocketpool/validators'/*`, otherwise the *-expansion fails if `validators` is not readable by the non-escalated user. To make sure we don't have misuse, we delete the getEscalationCmd, and add a function called readOutputSudo which does the same thing as readOutput, but first gets the appropriate escalation command (sudo or doas), and safely wraps the command in a `sudo/doas bash -c '%s'`

Fix commands that require escalation

---

docker/rocketpool-prune-provision
rocketpool-cli/service/service.go
rocketpool/prune_provision.sh
shared/services/config/smartnode-config.go
shared/services/rocketpool/client.go

Honestly, I haven't actually tested this, so preferably make sure it does what it should before releasing
Related PR: https://github.com/rocket-pool/smartnode-install/pull/144

Deprecate prune-provisioner container

---

rocketpool-cli/service/service.go
shared/services/rocketpool/client.go

Use curlimages/curl to begin nethermind prunes instead of a bespoke container.

Remove invocations to nethermind prune starter container, preferring docker-based curl

---

shared/services/config/external-configs.go
shared/services/config/lighthouse-config.go
shared/services/config/lodestar-config.go
shared/services/config/nimbus-config.go
shared/services/config/prysm-config.go
shared/services/config/teku-config.go
shared/services/rocketpool/assets/install/templates/eth2.tmpl
shared/services/rocketpool/assets/install/templates/validator.tmpl

Draft until https://github.com/rocket-pool/smartnode/pull/799 lands
All functional changes in https://github.com/rocket-pool/smartnode/pull/801/commits/7dc20decf183953f1cf7f800c4a1cf649fa6819f

Switch to building prysm containers locally from upstreams

---

rocketpool-cli/service/service.go
shared/services/config/rocket-pool-config.go
shared/services/rocketpool/assets/install/scripts/download-genesis.sh
shared/services/rocketpool/assets/install/scripts/start-bn.sh
shared/services/rocketpool/assets/install/scripts/start-vc.sh
shared/services/rocketpool/assets/install/templates/eth2.tmpl
shared/services/rocketpool/assets/install/templates/validator.tmpl

It turns out we don't need to build containers at all.
The last dependencies were:
1) prysm has /bin/bash but not /bin/sh available
2) we used `sed` in start-vc.sh to strip the scheme from the RPC URIs, if one is errantly provided.
3) we download genesis with wget for testnets
1 is easily fixed with templating around the entrypoint argument in docker-compose
2 is fixed by stripping the scheme in rocketpool-cli instead.
3 is fixed by using a new curlimages container to conditionally download genesis
This pr also fixes a broken hoodi genesis url

Use prysm containers directly

---

shared/services/rocketpool/assets/install/dashboards/Rocket Pool Dashboard v1.3.2.json
shared/services/rocketpool/assets/install/grafana-dashboards.yml
shared/services/rocketpool/assets/install/templates/grafana.tmpl
shared/services/rocketpool/assets/scripts/install.sh

The first commit copies the dashboard verbatim and provisions it with grafana automatically. 
The second commit makes it read-only, and removes the datasource input so the default is automatically used.
In the future we will not need to upload dashboards to grafana.com for docker users, but native mode users will still need to be able to get the json from somewhere. We can update the docs to point them to github, instead, and have them copy the json in directly.

Migrate grafana dashboard from smartnode-install, provision automatically

---

rocketpool-cli/node/claim-rewards.go
rocketpool-cli/node/utils.go
rocketpool-cli/odao/proposals.go
rocketpool-cli/pdao/proposals.go
rocketpool-cli/security/proposals.go
rocketpool-cli/service/config/standard-layout.go

There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: use slices.Contains to simplify code

---

Makefile
README.md
docker/daemon-bake.hcl
docker/rocketpool-dockerfile

This also removes the on-disk image targets because apparently when docker bake builds those, it doesn't include metadata (like entrypoint), which makes them beyond useless.

Add cli binaries to docker image

---

rocketpool-cli/service/service.go

See here for behavioral change: https://go.dev/play/p/1IBbAthKGW-
```
Old:
sigp/lighthouse:v110 -> lighthouse
gcr.io/offchainlabs/prysm/validator:v6.0.3 -> validator
New:
sigp/lighthouse:v110 -> sigp/lighthouse
gcr.io/offchainlabs/prysm/validator:v6.0.3 -> gcr.io/offchainlabs/prysm/validator
```
Basically, when we switched to the upstream prysm containers, a NO noticed that it triggered their 15 minute cooldown. This happened because the regex went from extracting `prysm` from `rocketpool/prysm` to extracting `validator` from `gcr.io/offchainlabs/prysm/validator:v6.0.3`
This is _bad_. Semantically, everything preceding the `:` is relevant to the specific image being used, and if orgs change their tag locations, we should still sit out for 15 minutes to be safe.

Update vc image regex to be less dangerous

---

rocketpool-cli/service/service.go
shared/services/rocketpool/client.go

Fixes an issue where the genesis downloader container prevented the volume from being released.
This should be genericized and added to resync-eth1, i think.

Dynamically find and delete containers using rocketpool_eth2clientdata when resync is run

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/unit-tests.yml
.golangci.yml
docker/rocketpool-dockerfile
go.mod
go.sum
shared/services/alerting/alerting.go
shared/services/rewards/generator-v8_test.go
shared/services/rewards/utils.go

I really want to use some new-as-of-1.22 features in the std http package, namely, the more advanced handler routing: https://go.dev/blog/routing-enhancements
Probably time we just update to latest stable.

Update golang to 1.24.5

---

rocketpool-cli/service/config/settings-alerting.go
shared/services/config/alertmanager-config.go

This pull request aims to fix the issue described below.
Steps to reproduce:
1. `make build/rocketpool-cli`
2. `cp build/rocketpool-cli ~/bin/rocketpool`
3. `rocketpool service install -d`
4. `rocketpool service config`
5. `rocketpool service get-config-yaml`
Expected result:
- YAML showing the current configuration schema is generated
Actual result:
Error is raised
```
panic: Duplicated key 'alertEnabled_ClientSyncStatusBeacon' in struct config.AlertmanagerConfig [recovered]
panic: Duplicated key 'alertEnabled_ClientSyncStatusBeacon' in struct config.AlertmanagerConfig
goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc0003a0498)
/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/yaml.go:249 +0x68
panic({0xf5b540?, 0xc0003d3010?})
/usr/local/go/src/runtime/panic.go:792 +0x132 …
```

Fix alertEnabled_ClientSyncStatusBeacon duplicated key issue

---

rocketpool/node/auto-init-voting-power.go
rocketpool/node/defend-pdao-props.go
rocketpool/node/distribute-minipools.go
rocketpool/node/promote-minipools.go
rocketpool/node/reduce-bonds.go
rocketpool/node/stake-prelaunch-minipools.go
rocketpool/node/verify-pdao-props.go
rocketpool/watchtower/process-penalties.go
rocketpool/watchtower/submit-rpl-price.go
shared/services/gas/etherchain/etherchain.go
shared/services/gas/etherscan/etherscan.go
shared/services/gas/gas.go

The smartnode uses mainnet gas oracle endpoints on testnet nodes. In some cases, hoodi transactions can be stuck when gas on mainnet is cheaper than gas on hoodi. 
This PR includes a few fixes: 
- Use the hoodi beaconcha.in gasnow endpoint on testnet nodes
- Support for Etherscan's updated gasnow api response structure 
- Remove unused code in `etherscan.go`

Use hoodi gas estimator url on testnet nodes. 

---

rocketpool-cli/service/service.go
shared/services/rocketpool/client.go

This PR is the same as https://github.com/nodeset-org/hyperdrive/pull/220 but adjusted for the rpl smartnode cli:
This PR is a small optimization that will pull the new docker container images before stopping the currently running ones, resulting in less downtime than before.
I've been bitten by having to wait for several containers to be pulled before, which are not only causing unnecessary downtime, but can be especially painful if one gets rate-limited by dockerhub, or when there are other failure modes in the image pull scenario. (e.g. docker disk full - which is not necessarily the same as where the data volumes live)
With this change the containers won't be stopped until the new images are available, potentially preventing these issues and improving uptime.
Old situation:
* User …

Feat: pull images before restart
